name: silva-notes
services:
  postgres:
    image: postgres:latest
    container_name: silva_notes_db
    environment:
      POSTGRES_USER: silvauser
      POSTGRES_PASSWORD: silvapass
      POSTGRES_DB: silvanotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  stripe-webhook:
    build:
      context: ./stripe
      dockerfile: Dockerfile
    container_name: silva_notes_stripe
    env_file:
      - ../.env
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    volumes:
      - ./stripe:/app
    depends_on:
      - postgres

volumes:
  postgres_data: